// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetGo.Persistence.Contexts;

#nullable disable

namespace NetGo.Persistence.Migrations
{
    [DbContext(typeof(NetGoDbContext))]
    [Migration("20240518160521_mig2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.19");

            modelBuilder.Entity("NetGo.Domain.Entities.Body", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bodies");
                });

            modelBuilder.Entity("NetGo.Domain.Entities.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BodyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.ToTable("Element");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Element");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NetGo.Domain.Entities.Child", b =>
                {
                    b.HasBaseType("NetGo.Domain.Entities.Element");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("Child");
                });

            modelBuilder.Entity("NetGo.Domain.Entities.Parent", b =>
                {
                    b.HasBaseType("NetGo.Domain.Entities.Element");

                    b.HasDiscriminator().HasValue("Parent");
                });

            modelBuilder.Entity("NetGo.Domain.Entities.Element", b =>
                {
                    b.HasOne("NetGo.Domain.Entities.Body", null)
                        .WithMany("Elements")
                        .HasForeignKey("BodyId");
                });

            modelBuilder.Entity("NetGo.Domain.Entities.Child", b =>
                {
                    b.HasOne("NetGo.Domain.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NetGo.Domain.Entities.Body", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("NetGo.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
